name: Build Apptainer Image

on:
  push:
    paths:
      - '**.def'  # Trigger only when a .def file is modified
  pull_request:
    paths:
      - '**.def'
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  build-image:
    runs-on: ubuntu-latest
    # Grant permissions to the GITHUB_TOKEN
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          # Define the version you want
          APP_VER="1.4.5"

          # Download the .deb package for the runner's architecture (usually amd64)
          curl -LO https://github.com/apptainer/apptainer/releases/download/v${APP_VER}/apptainer_${APP_VER}_amd64.deb

          # Use apt to install the local file
          # This automatically pulls in any missing dependencies like squashfs-tools
          sudo apt-get update
          sudo apt-get install -y ./apptainer_${APP_VER}_amd64.deb

          # Clean up the .deb file to save space
          rm apptainer_${APP_VER}_amd64.deb

      - name: Build Container
        run: |
          # If you have one specific file, use its name. 
          # This example builds 'container.def' into 'container.sif'
          # Using --fakeroot is necessary on GitHub runners
          apptainer build --fakeroot deacquest.sif deacquest.def


      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | apptainer remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io

      - name: Push to GHCR
        run: |
          apptainer push deacquest.sif oras://ghcr.io/wfu-hpc/deacquest:latest
